/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import myproject.Vehicle;
import java.*;
import java.io.Serializable;
import myproject.Company;
import myproject.MyException;

/**
 *
 * @author Abdelaziz
 */
public class AddNewVehicle extends javax.swing.JPanel implements Serializable {

    /**
     * Creates new form AddNewVehicle
     */
  
    MyException exc= new MyException();
    public AddNewVehicle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        choice1 = new java.awt.Choice();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabelBrand = new javax.swing.JLabel();
        jLabelModel = new javax.swing.JLabel();
        jLabelNumber = new javax.swing.JLabel();
        jLabelProductyear = new javax.swing.JLabel();
        jLabelSeatCapacity = new javax.swing.JLabel();
        jTextFieldBrand = new javax.swing.JTextField();
        jTextFieldModel = new javax.swing.JTextField();
        jTextFieldNumber = new javax.swing.JTextField();
        jTextFieldProductionYear = new javax.swing.JTextField();
        jTextFieldSeatCapacity = new javax.swing.JTextField();
        jLabelAnswer = new javax.swing.JLabel();
        jLabelEngineCapacity = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelType = new javax.swing.JLabel();
        jLabelVarient = new javax.swing.JLabel();
        jLabelRentValue = new javax.swing.JLabel();
        jTextFieldRentValue = new javax.swing.JTextField();
        jTextFieldEngineCapcaity = new javax.swing.JTextField();
        jComboBoxVarient = new javax.swing.JComboBox<>();
        jButtonAddCar = new javax.swing.JButton();
        jComboBoxType = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(153, 153, 255));

        jLabelBrand.setText("Brand");

        jLabelModel.setText("Model");

        jLabelNumber.setText("Number");

        jLabelProductyear.setText("Production Year");

        jLabelSeatCapacity.setText("Seat Capacity");

        jTextFieldBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBrandActionPerformed(evt);
            }
        });

        jTextFieldSeatCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSeatCapacityActionPerformed(evt);
            }
        });

        jLabelAnswer.setText("Please fill the following");

        jLabelEngineCapacity.setText("Engine Capacity");

        jLabel9.setText("jLabel9");

        jLabelType.setText("Type");

        jLabelVarient.setText("Varient");

        jLabelRentValue.setText("RentValue");

        jTextFieldEngineCapcaity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEngineCapcaityActionPerformed(evt);
            }
        });

        jComboBoxVarient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Base Model", "Economic Model", "Top Model" }));

        jButtonAddCar.setText("Add Car");
        jButtonAddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCarActionPerformed(evt);
            }
        });

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Non AC" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(82, 82, 82)
                                    .addComponent(jLabel9))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelProductyear)
                                    .addComponent(jLabelNumber)
                                    .addComponent(jLabelModel)
                                    .addComponent(jLabelBrand)
                                    .addComponent(jLabelSeatCapacity)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelType)
                                    .addComponent(jLabelEngineCapacity)
                                    .addComponent(jLabelVarient)
                                    .addComponent(jLabelRentValue))
                                .addGap(40, 40, 40)))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxVarient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldProductionYear, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSeatCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRentValue, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEngineCapcaity, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabelAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonAddCar)
                .addGap(264, 264, 264))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAnswer)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBrand)
                    .addComponent(jTextFieldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModel)
                    .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumber))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProductionYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProductyear))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSeatCapacity)
                    .addComponent(jTextFieldSeatCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEngineCapacity)
                    .addComponent(jTextFieldEngineCapcaity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelType)
                    .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxVarient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVarient))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRentValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRentValue))
                .addGap(40, 40, 40)
                .addComponent(jButtonAddCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBrandActionPerformed

    private void jTextFieldEngineCapcaityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEngineCapcaityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEngineCapcaityActionPerformed

    private void jTextFieldSeatCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSeatCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSeatCapacityActionPerformed

    private void jButtonAddCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCarActionPerformed
        // TODO add your handling code here:
        if(!jTextFieldBrand.getText().isEmpty()  &&  !jTextFieldModel.getText().isEmpty() && !jTextFieldNumber.getText().isEmpty() && !jTextFieldProductionYear.getText().isEmpty() && !jTextFieldSeatCapacity.getText().isEmpty() && !jTextFieldEngineCapcaity.getText().isEmpty() && !jTextFieldRentValue.getText().isEmpty() )                                                                      
        {
            
            
            Vehicle x = new Vehicle();
            String p;
            Company c = new Company();
            if(c.isExist(jTextFieldBrand.getText()))
            {       
            x.setBrand(c.SearchCompany(jTextFieldBrand.getText()));
 
            x.setCarModel(jTextFieldModel.getText());
            p= exc.ISnumeric(jTextFieldNumber.getText(),"NNUMBER");
            x.setNumber(Integer.parseInt(p));
            p= exc.ISnumeric(jTextFieldProductionYear.getText(),"production year");
            x.setProductionYear(Integer.parseInt(exc.checkPositive(p)));
            p= exc.ISnumeric(jTextFieldEngineCapcaity.getText(),"engine capacity");
            x.setEngineCapacity(Integer.parseInt(exc.checkPositive(p)));
            p= exc.ISnumeric(jTextFieldSeatCapacity.getText(),"seat capacity");
            x.setSeatCapacity(Integer.parseInt(exc.checkPositive(p)));
            p= exc.ISnumeric(jTextFieldRentValue.getText(),"Rent value");
            x.setRentValue(Integer.parseInt(exc.checkPositive(p)));
            
                                               /*varient*/
            if(jComboBoxVarient.getSelectedIndex() == 0)
            {
                x.setVarient("Base Model");
            
            }
            else if(jComboBoxVarient.getSelectedIndex() == 1) 
                {
                    x.setVarient("Economic Model");
                }
            else
                 x.setVarient("Top Model");
            
            
            
                                              /*  Type   */
            if (jComboBoxType.getSelectedIndex() == 0)
                x.setType("AC");
            else
                x.setType("Non AC");
            
           

          if(x.AddVehicle())
          {
              jLabelAnswer.setText("Added Successfully...");
              ResetPanel();
              
          }
          else
          {
              jLabelAnswer.setText("Failed to Insert..");
          }
          
          }
            else
                jLabelAnswer.setText("Company does not exist... Try again");
          
          
        }
        else
        jLabelAnswer.setText("Missing Required Data..!");
        
        
        
    }//GEN-LAST:event_jButtonAddCarActionPerformed

    
    public  void ResetPanel()
    {
        jTextFieldBrand.setText("");
        jTextFieldEngineCapcaity.setText("");
        jTextFieldModel.setText("");
        jTextFieldNumber.setText("");
        jTextFieldProductionYear.setText("");
        jTextFieldRentValue.setText("");
        jTextFieldSeatCapacity.setText("");
        
        jComboBoxType.setSelectedIndex(0);
        jComboBoxVarient.setSelectedIndex(0);
        
    
    
    
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private java.awt.Choice choice1;
    private javax.swing.JButton jButtonAddCar;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JComboBox<String> jComboBoxVarient;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAnswer;
    private javax.swing.JLabel jLabelBrand;
    private javax.swing.JLabel jLabelEngineCapacity;
    private javax.swing.JLabel jLabelModel;
    private javax.swing.JLabel jLabelNumber;
    private javax.swing.JLabel jLabelProductyear;
    private javax.swing.JLabel jLabelRentValue;
    private javax.swing.JLabel jLabelSeatCapacity;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JLabel jLabelVarient;
    private javax.swing.JTextField jTextFieldBrand;
    private javax.swing.JTextField jTextFieldEngineCapcaity;
    private javax.swing.JTextField jTextFieldModel;
    private javax.swing.JTextField jTextFieldNumber;
    private javax.swing.JTextField jTextFieldProductionYear;
    private javax.swing.JTextField jTextFieldRentValue;
    private javax.swing.JTextField jTextFieldSeatCapacity;
    // End of variables declaration//GEN-END:variables
}
