/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;
import java.*;
import java.io.Serializable;
import myproject.Company;

import myproject.Vehicle;

/**
 *
 * @author Abdelaziz
 */
public class Admin_VehicleUpdate extends javax.swing.JPanel implements Serializable {

    /**
     * Creates new form Admin_VehicleUpdate
     */
    public Admin_VehicleUpdate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButtonSearch = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jLabelModel = new javax.swing.JLabel();
        jLabelNumber = new javax.swing.JLabel();
        jLabelProductionYear = new javax.swing.JLabel();
        jLabelUseAS = new javax.swing.JLabel();
        jLabelSeatCapacity = new javax.swing.JLabel();
        jLabelEngineCapacity = new javax.swing.JLabel();
        jLabelType = new javax.swing.JLabel();
        jLabelBrand = new javax.swing.JLabel();
        jLabelVarient = new javax.swing.JLabel();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jTextFieldBrand = new javax.swing.JTextField();
        jTextFieldNumber = new javax.swing.JTextField();
        jTextFieldModel = new javax.swing.JTextField();
        jTextFieldProductionYear = new javax.swing.JTextField();
        jTextFieldSeatCapcaity = new javax.swing.JTextField();
        jTextFieldEngineCapcaity = new javax.swing.JTextField();
        jComboBoxVarient = new javax.swing.JComboBox<>();
        jLabelRentValue = new javax.swing.JLabel();
        jTextFieldRentValue = new javax.swing.JTextField();
        jLabelAnswer = new javax.swing.JLabel();
        jComboBoxUseAs = new javax.swing.JComboBox<>();
        jComboBoxType = new javax.swing.JComboBox<>();
        jLabelstatus = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 255));
        setToolTipText("");

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jLabelModel.setText("Model");

        jLabelNumber.setText("Number");

        jLabelProductionYear.setText("Production Year");

        jLabelUseAS.setText("Use As");

        jLabelSeatCapacity.setText("Seat Capacity");

        jLabelEngineCapacity.setText("Engine Capacity");

        jLabelType.setText("Type");

        jLabelBrand.setText("Brand");

        jLabelVarient.setText("Vairent");

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jTextFieldNumber.setEditable(false);

        jComboBoxVarient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Base Model", "Economic Model", "Top Model" }));

        jLabelRentValue.setText("Rent Value");

        jLabelAnswer.setText("Write Car Number To get it's info");

        jComboBoxUseAs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Taxi", "Individual" }));

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Non AC" }));

        jLabelstatus.setText("Status");

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rented", "Unrented" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jLabelEngineCapacity))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSeatCapacity, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelProductionYear, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelUseAS, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelModel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelBrand, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelRentValue, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelVarient, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelType, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelstatus, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldProductionYear, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                        .addComponent(jTextFieldSeatCapcaity)
                                        .addComponent(jTextFieldEngineCapcaity))
                                    .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxUseAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxVarient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jTextFieldRentValue, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearch)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabelAnswer)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumber)
                    .addComponent(jTextFieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBrand))
                .addGap(4, 4, 4)
                .addComponent(jButtonUpdate)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelModel)
                    .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jButtonDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProductionYear)
                    .addComponent(jTextFieldProductionYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelUseAS)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSeatCapacity)
                            .addComponent(jTextFieldSeatCapcaity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEngineCapcaity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEngineCapacity, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelType)
                            .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxVarient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelVarient))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRentValue)
                            .addComponent(jTextFieldRentValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBoxUseAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelstatus)
                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        if(!jTextFieldSearch.getText().equals(""))
        {
            Vehicle x = new Vehicle();
            if(x.DeleteVehicle(Integer.parseInt(jTextFieldSearch.getText())))
            {
                jLabelAnswer.setText("Vehicle Deleted Successfully ...");
                ResetPanel();
               
            }
            else 
            {
                jLabelAnswer.setText("Could'nt Delete ....!");
                
            }
        }
        else{
            jLabelAnswer.setText("Missing REQUIRED Field....!!!");
        
        }
        
        
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        if(!jTextFieldSearch.getText().equals(""))
        {
            Vehicle x = new Vehicle();
           
            Vehicle returned = x.SearchVehicle(Integer.parseInt(jTextFieldSearch.getText()));
            
            if(returned.getNumber() > 0)
            {
                SetPanel(returned);
                jLabelAnswer.setText("Found ...");
            }
            else {
                jLabelAnswer.setText("Not Found ");
            }
        }
        else jLabelAnswer.setText("Missing Required Field....!");
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
         if(   !jTextFieldBrand.getText().equals("") && !jTextFieldModel.getText().equals("") && !jTextFieldNumber.getText().equals("") && !jTextFieldProductionYear.getText().equals("") && !jTextFieldSeatCapcaity.getText().equals("") && !jTextFieldEngineCapcaity.getText().equals("") && !jTextFieldRentValue.getText().equals("") )                                                                      
        {
            Vehicle x = new Vehicle();
            Company c = new Company();
            if(c.isExist(jTextFieldBrand.getText()))
            {    
            
            x.setBrand(c.SearchCompany(jTextFieldBrand.getText()));
            x.setCarModel(jTextFieldModel.getText());
            x.setNumber(Integer.parseInt((jTextFieldNumber.getText())));
            x.setProductionYear(Integer.parseInt(jTextFieldProductionYear.getText()));
            x.setEngineCapacity(Integer.parseInt(jTextFieldEngineCapcaity.getText()));
            x.setSeatCapacity(Integer.parseInt(jTextFieldSeatCapcaity.getText()));
            x.setRentValue(Double.parseDouble(jTextFieldRentValue.getText()));
            
           if(jComboBoxVarient.getSelectedIndex() == 0)
            {
                x.setVarient("Base Model");
            
            }
            else if(jComboBoxVarient.getSelectedIndex() == 1) 
                {
                    x.setVarient("Economic Model");
                }
            else
                 x.setVarient("Top Model");
         
           
            if(jComboBoxStatus.getSelectedIndex() == 0)
            {
                x.setStatus("Rented");
            }            
            else 
                x.setStatus("Unrented");
            
        
            if(jComboBoxUseAs.getSelectedIndex() == 0)
             x.setUseAs("Taxi");
            else 
                x.setUseAs("Individual");
            
            
            if (jComboBoxType.getSelectedIndex() == 0)
                x.setType("AC");
            else
                x.setType("Non AC");
            
            
            if(x.UpdateVehicle())
            {
                jLabelAnswer.setText("Vehicle Updated Successfully....");
                ResetPanel();
            
            }
            else
            {
                jLabelAnswer.setText("Couldn't Update  !");
            }
            
            }
            else
               jLabelAnswer.setText("Company couldn't  be found...Add car within the existing Companies and brands");
            }
         else
         {
             jLabelAnswer.setText("Missing Required Field  !");
         }
            
            
    }//GEN-LAST:event_jButtonUpdateActionPerformed

         
    
    
    public void SetPanel(Vehicle x)
    {
        jTextFieldBrand.setText("" + x.getBrand().getBrand());
        jTextFieldModel.setText("" + x.getCarModel());
        jTextFieldNumber.setText(""+ x.getNumber());
        jTextFieldProductionYear.setText(""+ x.getProductionYear());
        jTextFieldEngineCapcaity.setText(""+ x.getEngineCapacity());
        jTextFieldSeatCapcaity.setText(""+ x.getSeatCapacity());
        jTextFieldRentValue.setText(""+ x.getRentValue());
        
        
        if(x.getType().equals("AC"))
        {
            jComboBoxType.setSelectedIndex(0);
        }else jComboBoxType.setSelectedIndex(1);
        
        if(x.getUseAs().equals("Taxi"))
        {
            jComboBoxUseAs.setSelectedIndex(0);
        }else 
            jComboBoxUseAs.setSelectedIndex(1);
        
       
        if(x.getVarient().equals("Base Model"))
        {
            jComboBoxVarient.setSelectedIndex(0);
        }
        else{
            if(x.getVarient().equals("Economic Model"))
            {
                jComboBoxVarient.setSelectedIndex(1);
            }
            else
                jComboBoxVarient.setSelectedIndex(2);
        }
        
        if(x.getStatus().equals("Unrented"))
        {
            jComboBoxStatus.setSelectedIndex(1);
        }
        else
            jComboBoxStatus.setSelectedIndex(0);
        
    }
    
     public  void ResetPanel()
    {
        jTextFieldBrand.setText("");
        jTextFieldEngineCapcaity.setText("");
        jTextFieldModel.setText("");
        jTextFieldNumber.setText("");
        jTextFieldProductionYear.setText("");
        jTextFieldRentValue.setText("");
        jTextFieldSeatCapcaity.setText("");
        
        
        jComboBoxType.setSelectedIndex(0);
        jComboBoxUseAs.setSelectedIndex(0);
        jComboBoxVarient.setSelectedIndex(0);
        jComboBoxStatus.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JComboBox<String> jComboBoxUseAs;
    private javax.swing.JComboBox<String> jComboBoxVarient;
    private javax.swing.JLabel jLabelAnswer;
    private javax.swing.JLabel jLabelBrand;
    private javax.swing.JLabel jLabelEngineCapacity;
    private javax.swing.JLabel jLabelModel;
    private javax.swing.JLabel jLabelNumber;
    private javax.swing.JLabel jLabelProductionYear;
    private javax.swing.JLabel jLabelRentValue;
    private javax.swing.JLabel jLabelSeatCapacity;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JLabel jLabelUseAS;
    private javax.swing.JLabel jLabelVarient;
    private javax.swing.JLabel jLabelstatus;
    private javax.swing.JTextField jTextFieldBrand;
    private javax.swing.JTextField jTextFieldEngineCapcaity;
    private javax.swing.JTextField jTextFieldModel;
    private javax.swing.JTextField jTextFieldNumber;
    private javax.swing.JTextField jTextFieldProductionYear;
    private javax.swing.JTextField jTextFieldRentValue;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldSeatCapcaity;
    // End of variables declaration//GEN-END:variables
}
