/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import myproject.Vehicle;
import java.*;
import java.io.Serializable;

/**
 *
 * @author Abdelaziz
 */
public class Admin_ListVehicles extends javax.swing.JPanel implements Serializable{

    /**
     * Creates new form Admin_ListVehicles
     */
    public Admin_ListVehicles() {
        initComponents();
        AddTableRows();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Brand", "Model", "Production Year", "Seat Capacity", "Engine Capacity", "Type", "Varient", "Status", "UseType", "Rent Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

public void AddTableRows()
{
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    
    Object RowData [] = new Object[11];
    
    Vehicle v =new Vehicle();
    
    ArrayList<Vehicle> vehicles = new ArrayList<Vehicle>();
    
    vehicles = v.listVehicles();
    
    int rowCount = model.getRowCount();
    for (int i = rowCount - 1; i >= 0; i--) {
        model.removeRow(i);
}
    
    for(Vehicle x : vehicles )
    {
        RowData[0] = x.getNumber();
        RowData[1] =x.getBrand().getBrand();
        RowData[2] =x.getCarModel();
        RowData[3] =x.getProductionYear();
        RowData[4] = x.getSeatCapacity();
        RowData[5] =x.getEngineCapacity();
        RowData[6] =x.getType();
        RowData[7] =x.getVarient();
        RowData[8] = x.getStatus();
        RowData[9] =x.getUseAs();
        RowData[10] =x.getRentValue();
       
        model.addRow(RowData);
    }
    
}
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
