/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import myproject.Driver;


/**
 *
 * @author SYSTEM
 */
public class Driver_Listpanel extends javax.swing.JPanel implements Serializable {

    /**
     * Creates new form Driver_Listpanel
     */
    public Driver_Listpanel() {
        initComponents();
        addRowsTojTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Gender", "phone.NO", "Address", "BirthDate", "Experience", "Salary", "Client"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public void addRowsTojTable()
    {
    DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
    Object rowdata[]=new Object[20];
    Driver dr=new Driver ();
    ArrayList<Driver> drivers=new ArrayList<Driver>();
    drivers =dr.listDrivers();
    
    int rowCount = model.getRowCount();
    for (int i = rowCount - 1; i >= 0; i--) {
        model.removeRow(i);
}
    
    
    for (Driver x :drivers)
    {
    rowdata[0]=x.getName();
    rowdata[1]=x.getID();
    rowdata[2]=x.getGender();
    rowdata[3]=x.getPhoneNumber();
    rowdata[4]=x.getAddress();
    rowdata[5]=x.getDateOfBirth();
    rowdata[6]=x.getExprience();
    rowdata[7]=x.getSalary();
    rowdata[8]=x.getClient().getID();
    model.addRow(rowdata);
    
    }
    
    }
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
