/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import myproject.Customer;
import java.*;
import java.io.Serializable;
import java.text.DateFormat;
import javax.mail.MessagingException;
import myproject.Driver;
import myproject.Email;
import myproject.Vehicle;
import myproject.MyException;
import myproject.Ticket;

/**
 *
 * @author mohamed
 */
public class employee_addcustomer_panel extends javax.swing.JPanel implements Serializable {

    /**
     * Creates new form employee_addcustomer_panel
     */
    public MyException exc=new MyException();
     Email E;
     Ticket T;
    public employee_addcustomer_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customergender = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        customername = new javax.swing.JTextField();
        customeraddress = new javax.swing.JTextField();
        customerphonenumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        customeriD = new javax.swing.JTextField();
        customerDays = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Insertcustomer = new javax.swing.JButton();
        selectGender = new javax.swing.JComboBox<>();
        jTextFieldRentedCarID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxUseAs = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jDateChooserBookdDate = new org.netbeans.modules.form.InvalidComponent();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("Name");

        jLabel2.setText("Gender");

        jLabel3.setText("Address");

        jLabel4.setText("PhoneNumber");

        customeriD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customeriDActionPerformed(evt);
            }
        });

        jLabel5.setText("ID");

        jLabel6.setText("DaysOfRenting");

        jLabel7.setText("BookDate");

        Insertcustomer.setText("Add customer");
        Insertcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertcustomerActionPerformed(evt);
            }
        });

        selectGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));
        selectGender.setSelectedIndex(-1);
        selectGender.setToolTipText("select gender");

        jTextFieldRentedCarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRentedCarIDActionPerformed(evt);
            }
        });

        jLabel8.setText("RentedCarID");

        jComboBoxUseAs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Taxi", "Individual" }));

        jLabel9.setText("Use As");

        jLabelEmail.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectGender, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(customeriD, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(customername)
                            .addComponent(customeraddress, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldRentedCarID)
                            .addComponent(jTextFieldEmail)
                            .addComponent(customerphonenumber)
                            .addComponent(customerDays)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxUseAs, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jDateChooserBookdDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(Insertcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(selectGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(customeriD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(customeraddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(customerDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(customerphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel7))
                    .addComponent(jDateChooserBookdDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldRentedCarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEmail)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxUseAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addGap(29, 29, 29)
                .addComponent(Insertcustomer)
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InsertcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertcustomerActionPerformed
        
        if(!jTextFieldRentedCarID.getText().equals("") && !customername.getText().equals("")&&!customeraddress.getText().equals("")&&!customerphonenumber.getText().equals("")&&!customeriD.getText().equals("")&&selectGender.getSelectedIndex()!= -1 &&!customerDays.getText().equals("")&&!jTextFieldEmail.getText().equals(""))
        {
            Customer x = new Customer();
            Vehicle y=new Vehicle();
            boolean b1=true,b6=true;
            Vehicle returned =y.SearchVehicle(Integer.parseInt(exc.ISnumeric(jTextFieldRentedCarID.getText(),"Vehicle ID")));
            if(returned.getNumber()>0 && returned.getStatus().equals("Unrented"))
            {

              String f=exc.ISnumeric(customeriD.getText(),"Customer ID");
            x.setID(Integer.parseInt(exc.checkPositive(f)));
            x.setAddress(customeraddress.getText());
            x.setName(customername.getText());
            String m=exc.ISnumeric((customerphonenumber.getText()),"Phone Number");
            x.setPhoneNumber(exc.checkPositive(m));
            x.setNumbersOfRentingDays(Integer.parseInt(exc.ISnumeric(customerDays.getText(),"Number of Renting days")));
             m=exc.ISnumeric(customerDays.getText(),"Number Of renting Days");
             x.setNumbersOfRentingDays(Integer.parseInt(exc.checkPositive(m)));
//                boolean b2;
//            if(x.getNumbersOfRentingDays()<0)
//            {
//                b2=false;
//            }
//            else
//                b2=true;
            
                x.setCustomerMail(exc.checkEmail(jTextFieldEmail.getText(),"Customer Email"));
            
                
                
                
            boolean b=true;
            try{
            SimpleDateFormat dateFormat=new SimpleDateFormat("dd-MM-yyyy");
            String s=dateFormat.format(jDateChooserBookdDate.getDate());
            x.setBookDate(s);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"No date selected");
                b=false;
            }

            if(selectGender.getSelectedIndex() == 0)
            {
                x.setGender("male");
            } else if (selectGender.getSelectedIndex() == 1)
            {
                x.setGender("female");
            }
            
            int ay=returned.getNumberofRentingTimes();
            returned.setNumberofRentingTimes(ay+=1);
            
            returned.setStatus("Rented");
             Driver D=new Driver();
            if(jComboBoxUseAs.getSelectedIndex()== 0){
            returned.setUseAs("Taxi");
           Driver d = new Driver();
          
         D = d.FreeDriver();
         if(D.getID() > 0)
         {
                          
                          
           
            int p=returned.getTaxiTimes();
            returned.setTaxiTimes(p+=1);
            returned.UpdateVehicle();
            
             D.setFree(1);
             D.setClient(x);
             D.setCar(returned);
            b1 = D.UpdateDriver();

             
         }
         else
         { 
             JOptionPane.showMessageDialog(null,"No available Drivers");
             b1=false;
         }
            }
            else
            {
            returned.setUseAs("Individual");
            int c=returned.getIndividualTimes();
            returned.setIndividualTimes(c+=1);
            }
            
            
            if(!returned.UpdateVehicle())
            {
                b6 = false;
            }
            
            x.setRentedCar(returned);
            
            
            
            if(b6 == true && b1 == true && b==true && x.AddCustomer())
            {
                DateFormat df=new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
                Date dd=new Date();
                JOptionPane.showMessageDialog(null,"Added Succefully....");
                T=new Ticket(x.getRentedCar(),x,D);
                E=new Email(T.getCustomer().getCustomerMail(),"abdulazizfci97@gmail.com","Ticket","Ticket:"+T.getID()+""+"Date:"+df.format(dd)+""+"Cusomer Name:"+T.getCustomer().getName()+""+"Car Model:"+T.getCar().getCarModel()+""+"Total Price:"+T.TotalPrice());
                  try {
                      E.generateAndSendEmail();
                  } catch (MessagingException ex) {
                      Logger.getLogger(employee_addcustomer_panel.class.getName()).log(Level.SEVERE, null, ex);
                  }
                resetform();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Failed to add....");
               
            }
            
        }
            else
                JOptionPane.showMessageDialog(null,"Vehicle Not Found or Rented Already....");
        }
        else
            JOptionPane.showMessageDialog(null,"Missing required elements...Please complete them!");
    }//GEN-LAST:event_InsertcustomerActionPerformed

    private void jTextFieldRentedCarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRentedCarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRentedCarIDActionPerformed

    private void customeriDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customeriDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customeriDActionPerformed
    
    protected void resetform()
    {
        customeriD.setText("");
        customeraddress.setText("");
        customername.setText("");
        customerphonenumber.setText("");
        customerDays.setText("");
        jDateChooserBookdDate.setCalendar(null);
        selectGender.setSelectedIndex(-1);
        jTextFieldEmail.setText("");
        jTextFieldRentedCarID.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Insertcustomer;
    private javax.swing.JTextField customerDays;
    private javax.swing.JTextField customeraddress;
    private javax.swing.JTextField customergender;
    private javax.swing.JTextField customeriD;
    private javax.swing.JTextField customername;
    private javax.swing.JTextField customerphonenumber;
    private javax.swing.JComboBox<String> jComboBoxUseAs;
    private org.netbeans.modules.form.InvalidComponent jDateChooserBookdDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldRentedCarID;
    private javax.swing.JComboBox<String> selectGender;
    // End of variables declaration//GEN-END:variables
}
