/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import myproject.Customer;
import myproject.Vehicle;
import java.*;
import java.io.Serializable;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import myproject.Driver;
import myproject.MyException;
/**
 *
 * @author mohamed
 */
public class employee_returncar_panel extends javax.swing.JPanel implements Serializable {

    /**
     * Creates new form employee_returncar_panel
     */
    Customer handle;
    MyException exc=new MyException();
    public employee_returncar_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jTextFieldCustomer = new javax.swing.JTextField();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldNumber = new javax.swing.JTextField();
        jDateChooserDate = new com.toedter.calendar.JDateChooser();
        jLabelID = new javax.swing.JLabel();
        jLabelCName = new javax.swing.JLabel();
        jLabelVehicel = new javax.swing.JLabel();
        jLabelBookDate = new javax.swing.JLabel();
        jButtonReturn = new javax.swing.JButton();
        jLabelAnswer = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jTextFieldCustomer.setEditable(false);

        jTextFieldID.setEditable(false);

        jTextFieldNumber.setEditable(false);

        jLabelID.setText("Customer ID");

        jLabelCName.setText("Customer Name");

        jLabelVehicel.setText("Vehicle Number");

        jLabelBookDate.setText("Book Date");

        jButtonReturn.setText("Return");
        jButtonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnActionPerformed(evt);
            }
        });

        jLabelAnswer.setText("Search Customer By ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelCName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelVehicel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabelBookDate, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonReturn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldCustomer)
                                .addComponent(jTextFieldID)
                                .addComponent(jTextFieldNumber)
                                .addComponent(jDateChooserDate, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabelAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch))
                .addGap(18, 18, 18)
                .addComponent(jLabelAnswer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBookDate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelID))
                                .addGap(30, 30, 30)
                                .addComponent(jTextFieldCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelCName))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelVehicel))
                        .addGap(37, 37, 37)
                        .addComponent(jDateChooserDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addComponent(jButtonReturn)
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        if(!jTextFieldSearch.getText().equals(""))
        {
            Customer c= new Customer();
            Vehicle x = new Vehicle();
            
            Customer returned = c.SearchCustomer(Integer.parseInt(jTextFieldSearch.getText()));
            
            if(returned.getID() > 0)
            { 
                jTextFieldID.setText("" + returned.getID());
                jTextFieldCustomer.setText("" + returned.getName());
                jTextFieldNumber.setText("" + returned.getRentedCar().getNumber());
                
                 
        Date d = null;
        try {
            d=new SimpleDateFormat("dd-MM-yyyy").parse(returned.getBookDate());
        } catch (ParseException ex) {
            Logger.getLogger(UpdateandDeleteEmployee.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Wrong date");
        }
       jDateChooserDate.setDate(d);
                
               jLabelAnswer.setText("Found ...");

                
            }
            else 
                jLabelAnswer.setText("ID not Found......");  
            
        }
        else 
            jLabelAnswer.setText("Fill The Search Field");
       
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnActionPerformed
        // TODO add your handling code here:
        
       if(!jTextFieldNumber.getText().equals("")) 
       {
        Customer c = new Customer();
        Vehicle v = new Vehicle();
        Driver d = new Driver();
        Customer Returned = c.SearchCustomer(Integer.parseInt(jTextFieldSearch.getText()));
        Vehicle returned = v.SearchVehicle(Returned.getRentedCar().getNumber());
       
        Driver D  = d.DriverCar(returned.getNumber());
        
        if(D.getCar().getNumber() > 0)
        {
            D.setFree(0);
            Vehicle temp = new Vehicle();
            D.setCar(temp);
            Customer f = new Customer();
            D.setClient(f);
        }
       
       
        if(Returned.getID()>0)
        {    
        returned.setStatus("Unrented");
        returned.setUseAs("");
        
        Vehicle tmp=new Vehicle();
        Returned.setRentedCar(tmp);
        
        if(D.UpdateDriver() && Returned.UpdateCustomer()&&returned.UpdateVehicle()){
        resetPanel();
        jLabelAnswer.setText("Vehicle Returned Successfully");
        }
       }
        else
            jLabelAnswer.setText("ID not Found");
       }
       else
           jLabelAnswer.setText("Enter a valid Customer ID.....");
       
    }//GEN-LAST:event_jButtonReturnActionPerformed
    
    
    void resetPanel()
    {
        jTextFieldCustomer.setText("");
        jTextFieldID.setText("");
        jTextFieldNumber.setText("");
        jTextFieldSearch.setText("");
        jDateChooserDate.setCalendar(null);
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReturn;
    private javax.swing.JButton jButtonSearch;
    private com.toedter.calendar.JDateChooser jDateChooserDate;
    private javax.swing.JLabel jLabelAnswer;
    private javax.swing.JLabel jLabelBookDate;
    private javax.swing.JLabel jLabelCName;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelVehicel;
    private javax.swing.JTextField jTextFieldCustomer;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNumber;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
