/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import myproject.Customer;
import java.*;
import java.io.Serializable;
/**
 *
 * @author mohamed
 */
public class employee_listcustomer_panel extends javax.swing.JPanel  implements Serializable{

    /**
     * Creates new form employee_listcustomer_panel
     */
    public employee_listcustomer_panel() {
        initComponents();
        addrowtotable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Gender", "phone", "address", "Number Days", "BookDate", "RentedCar", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void addrowtotable(){
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object row[] = new Object[9];
        Customer c = new Customer();
       ArrayList<Customer> customers = new ArrayList<>();
       customers = c.ListCustomer();
      
       int rowCount = model.getRowCount();
       for (int i = rowCount - 1; i >= 0; i--) {
       model.removeRow(i);
}
       
       
       for(Customer x : customers){
           row[0] = x.getID();
           row[1] = x.getName();
           row[2] = x.getGender();
           row[3] = x.getPhoneNumber();           
           row[4] = x.getAddress();
           row[5] = x.getNumbersOfRentingDays(); 
           row[6] = x.getBookDate();
           row[7] = x.getRentedCar().getNumber();
           row[8] = x.getCustomerMail();
           model.addRow(row);
       }
       
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
