/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;
import java.*;
import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import myproject.Employee;

/**
 *
 * @author 3bqrano
 */
public class ListAllEmployee extends javax.swing.JPanel implements Serializable {

    /**
     * Creates new form ListAllEmployee
     */
    public ListAllEmployee() {
        initComponents();
        addRowstoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAdmin_Employee = new javax.swing.JTable();

        jTableAdmin_Employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Gender", "Address", "Phone", "Qualification", "Dateofjoin", "Dateofbirth", "UserName", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAdmin_Employee);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAdmin_Employee;
    // End of variables declaration//GEN-END:variables

    public void addRowstoTable() {
         //To change body of generated methods, choose Tools | Templates.
       DefaultTableModel model = (DefaultTableModel) jTableAdmin_Employee.getModel();
        Object rowData[] = new Object[9]; 
        Employee x = new Employee();
        ArrayList<Employee> Employees = new ArrayList<Employee>();
      
        
        
        Employees =x.ListEmployee();
        
        int rowCount = model.getRowCount();
for (int i = rowCount - 1; i >= 0; i--) {
    model.removeRow(i);
}
        
        for (Employee c : Employees){
            rowData[0] = c.getName();
            rowData[1] = c.getGender();
            rowData[2] = c.getAddress();
            rowData[3] = c.getPhoneNumber();
            rowData[4] = c.getQualification();
            rowData[5] = c.getDateOfJoin();
            rowData[6] = c.getDateOfBirth();
            rowData[7] = c.getUserName();
            rowData[8] = c.getPassword();
            model.addRow(rowData);
        }
       
        
    }
}
