/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrames;
import java.*;
import Panels.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import myproject.Driver;

/**
 *
 * @author Dell
 */
public class Admin_Driver extends javax.swing.JInternalFrame {

    /**
     * Creates new form Admin_Driver
     */
    public Admin_Driver() {
        initComponents();
        addRowsTojTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Driver_List = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 153, 255));
        setClosable(true);

        Driver_List.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Gender", "Phone", "Address", "D.O.B", "Experience", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Driver_List);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
      public void addRowsTojTable()
    {
    DefaultTableModel model = (DefaultTableModel)Driver_List.getModel();
    Object rowdata[]=new Object[20];
    
    Driver dr=new Driver ();
    
    
    ArrayList<Driver> drivers=new ArrayList<Driver>();
   
    
    drivers =dr.listDrivers();
   
    int rowCount = model.getRowCount();
for (int i = rowCount - 1; i >= 0; i--) {
    model.removeRow(i);
}
    
    for (Driver x :drivers)
    {
        
    rowdata[0]=x.getID();
    rowdata[1]=x.getName();
    rowdata[2]=x.getGender();
    rowdata[3]=x.getPhoneNumber();
    rowdata[4]=x.getAddress();
    rowdata[5]=x.getDateOfBirth();
    rowdata[6]=x.getExprience();
    rowdata[7]=x.getSalary();
    model.addRow(rowdata);
    
    }
    
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Driver_List;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables


}
