/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrames;
import Panels.*;
import java.*;
import Panels.AddNewEmployee;
import Panels.ListAllEmployee;
import Panels.UpdateandDeleteEmployee;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author 3bqrano
 */
public class Admin_Employee extends javax.swing.JInternalFrame {

    /**
     * Creates new form Admin_Employee
     */
    
    AddNewEmployee p1;
    ListAllEmployee p2;
    UpdateandDeleteEmployee p3;
    GridBagLayout layout = new GridBagLayout();
    
    
    public Admin_Employee() {
        initComponents();
        p1 = new AddNewEmployee();
        p2 = new ListAllEmployee();
        p3 = new UpdateandDeleteEmployee();
        DynamicPanelEmployee.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        DynamicPanelEmployee.add(p1 , c);
        DynamicPanelEmployee.add(p2 , c);
        DynamicPanelEmployee.add(p3 , c);
        
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonAddEmployee = new javax.swing.JButton();
        jButtonListAllEmployee = new javax.swing.JButton();
        jButtonUpdateandDelete = new javax.swing.JButton();
        DynamicPanelEmployee = new javax.swing.JPanel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jButtonAddEmployee.setText("AddEmployee");
        jButtonAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddEmployeeActionPerformed(evt);
            }
        });

        jButtonListAllEmployee.setText("ListAllEmployee");
        jButtonListAllEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListAllEmployeeActionPerformed(evt);
            }
        });

        jButtonUpdateandDelete.setText("Update/Delete");
        jButtonUpdateandDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateandDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonAddEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonListAllEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUpdateandDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jButtonAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(jButtonListAllEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(jButtonUpdateandDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        DynamicPanelEmployee.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout DynamicPanelEmployeeLayout = new javax.swing.GroupLayout(DynamicPanelEmployee);
        DynamicPanelEmployee.setLayout(DynamicPanelEmployeeLayout);
        DynamicPanelEmployeeLayout.setHorizontalGroup(
            DynamicPanelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        DynamicPanelEmployeeLayout.setVerticalGroup(
            DynamicPanelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );

        getContentPane().add(DynamicPanelEmployee, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddEmployeeActionPerformed
        // TODO add your handling code here:
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
    }//GEN-LAST:event_jButtonAddEmployeeActionPerformed

    private void jButtonListAllEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListAllEmployeeActionPerformed
        // TODO add your handling code here:
        
        p2.setVisible(true);
        p1.setVisible(false);
        p3.setVisible(false);
        p2.addRowstoTable();
    }//GEN-LAST:event_jButtonListAllEmployeeActionPerformed

    private void jButtonUpdateandDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateandDeleteActionPerformed
        // TODO add your handling code here:
        p3.setVisible(true);
        p1.setVisible(false);
        p2.setVisible(false);
    }//GEN-LAST:event_jButtonUpdateandDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanelEmployee;
    private javax.swing.JButton jButtonAddEmployee;
    private javax.swing.JButton jButtonListAllEmployee;
    private javax.swing.JButton jButtonUpdateandDelete;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
