/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrames;
import Panels.*;
import java.*;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import Panels.employee_addcustomer_panel;
import Panels.employee_listcustomer_panel;
import Panels.employee_updatecustomer_panel;
import javax.swing.JOptionPane;

/**
 *
 * @author mohamed
 */
public class Employee_Customer extends javax.swing.JInternalFrame {

    /**
     * Creates new form Employee_Customer
     */
    employee_addcustomer_panel p1;
    employee_listcustomer_panel p2;
    employee_returncar_panel p4;
    employee_updatecustomer_panel p3;
    GridBagLayout layout = new GridBagLayout();
    public Employee_Customer() {
        initComponents();
        p1 = new employee_addcustomer_panel();
        p2 = new employee_listcustomer_panel();
        p4 = new employee_returncar_panel();
        p3 = new employee_updatecustomer_panel();
        Dynamicemployeewithcustomer.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        
        Dynamicemployeewithcustomer.add(p1,c);
        Dynamicemployeewithcustomer.add(p2,c);
        Dynamicemployeewithcustomer.add(p3,c);
        Dynamicemployeewithcustomer.add(p4,c);
        
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addcutomerB = new javax.swing.JButton();
        listcustomerB = new javax.swing.JButton();
        updatecustomerB = new javax.swing.JButton();
        retuencarB = new javax.swing.JButton();
        Dynamicemployeewithcustomer = new javax.swing.JPanel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        addcutomerB.setText("Add Customer");
        addcutomerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcutomerBActionPerformed(evt);
            }
        });

        listcustomerB.setText("List Customers");
        listcustomerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listcustomerBActionPerformed(evt);
            }
        });

        updatecustomerB.setText("Update / Delete");
        updatecustomerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatecustomerBActionPerformed(evt);
            }
        });

        retuencarB.setText("Return Car");
        retuencarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retuencarBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updatecustomerB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(retuencarB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listcustomerB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addcutomerB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(addcutomerB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(listcustomerB)
                .addGap(97, 97, 97)
                .addComponent(updatecustomerB)
                .addGap(121, 121, 121)
                .addComponent(retuencarB)
                .addGap(197, 197, 197))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        Dynamicemployeewithcustomer.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout DynamicemployeewithcustomerLayout = new javax.swing.GroupLayout(Dynamicemployeewithcustomer);
        Dynamicemployeewithcustomer.setLayout(DynamicemployeewithcustomerLayout);
        DynamicemployeewithcustomerLayout.setHorizontalGroup(
            DynamicemployeewithcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        DynamicemployeewithcustomerLayout.setVerticalGroup(
            DynamicemployeewithcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );

        getContentPane().add(Dynamicemployeewithcustomer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addcutomerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcutomerBActionPerformed
       
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
         JOptionPane.showMessageDialog(null,"Enter customer data");
        
    }//GEN-LAST:event_addcutomerBActionPerformed

    private void listcustomerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listcustomerBActionPerformed
        
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
        p2.addrowtotable();
        
    }//GEN-LAST:event_listcustomerBActionPerformed

    private void updatecustomerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatecustomerBActionPerformed
        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
        JOptionPane.showMessageDialog(null,"Search customer ID before updating or deleting");
    }//GEN-LAST:event_updatecustomerBActionPerformed

    private void retuencarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retuencarBActionPerformed
        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
        JOptionPane.showMessageDialog(null,"Search Customer ID ..");
    }//GEN-LAST:event_retuencarBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dynamicemployeewithcustomer;
    private javax.swing.JButton addcutomerB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton listcustomerB;
    private javax.swing.JButton retuencarB;
    private javax.swing.JButton updatecustomerB;
    // End of variables declaration//GEN-END:variables
}
