/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrames;

import Panels.Driver_Addpanel;
import Panels.Driver_Listpanel;
import Panels.Driver_Updatepanel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author toshiba
 */
public class Employee_Driver extends javax.swing.JInternalFrame {

    /**
     * Creates new form Employee_Driver
     */
    
    
    Driver_Addpanel p1;
    Driver_Listpanel p2;
    Driver_Updatepanel p3;
    GridBagLayout layout= new GridBagLayout();
    public Employee_Driver() {
        initComponents();

        p1=new Driver_Addpanel();
        p2=new Driver_Listpanel();
        p3=new Driver_Updatepanel();
        
        
        Dynamic.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
    
    
   Dynamic.add(p1,c);
   Dynamic.add(p2,c);
    Dynamic.add(p3,c);
    
    
    p1.setVisible(true);
    p2.setVisible(false);
    p3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1AddDriver = new javax.swing.JButton();
        jButtonListDriver = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        Dynamic = new javax.swing.JPanel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jButton1AddDriver.setText("Add Driver");
        jButton1AddDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AddDriverActionPerformed(evt);
            }
        });

        jButtonListDriver.setText("List Driver");
        jButtonListDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListDriverActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update/Delete");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonListDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1AddDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton1AddDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(jButtonListDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        Dynamic.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout DynamicLayout = new javax.swing.GroupLayout(Dynamic);
        Dynamic.setLayout(DynamicLayout);
        DynamicLayout.setHorizontalGroup(
            DynamicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        DynamicLayout.setVerticalGroup(
            DynamicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );

        getContentPane().add(Dynamic, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1AddDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AddDriverActionPerformed
        // TODO add your handling code here:
       
    p1.setVisible(true);
    p2.setVisible(false);
    p3.setVisible(false);
    }//GEN-LAST:event_jButton1AddDriverActionPerformed

    private void jButtonListDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListDriverActionPerformed
        // TODO add your handling code here:
     p1.setVisible(false);
    p2.setVisible(true);
    p3.setVisible(false);
    p2.addRowsTojTable();
    
    }//GEN-LAST:event_jButtonListDriverActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
    p1.setVisible(false);
    p2.setVisible(false);
    p3.setVisible(true);
    }//GEN-LAST:event_jButtonUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dynamic;
    private javax.swing.JButton jButton1AddDriver;
    private javax.swing.JButton jButtonListDriver;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
