/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



 //     This Frame is  Not Used 
package InternalFrames;
import Panels.Driver_Addpanel;
import Panels.*;
import Panels.Driver_Updatepanel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.*;
/**
 *
 * @author SYSTEM
 */
public class Employee_Driverframe extends javax.swing.JInternalFrame {

    /**
     * Creates new form Employee_Driverframe
     */
    
    Driver_Addpanel p1;
    Driver_Listpanel p2;
    Driver_Updatepanel p3;
    
   GridBagLayout layout= new GridBagLayout();
    public Employee_Driverframe() {
        initComponents();
        p1=new Driver_Addpanel();
        p2=new Driver_Listpanel();
        p3=new Driver_Updatepanel();
        
        
        Dynamic.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
    
    
   Dynamic.add(p1,c);
   Dynamic.add(p2,c);
    Dynamic.add(p3,c);
    
    
    p1.setVisible(true);
    p2.setVisible(false);
    p3.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Dynamic = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1AddD = new javax.swing.JButton();
        jButton2ListD = new javax.swing.JButton();
        jButtonupdateD = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));

        jButton1AddD.setText("Add Driver");
        jButton1AddD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AddDActionPerformed(evt);
            }
        });

        jButton2ListD.setText("List Driver");
        jButton2ListD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ListDActionPerformed(evt);
            }
        });

        jButtonupdateD.setText("Update Driver");
        jButtonupdateD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonupdateDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2ListD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1AddD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonupdateD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jButton1AddD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(jButton2ListD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jButtonupdateD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DynamicLayout = new javax.swing.GroupLayout(Dynamic);
        Dynamic.setLayout(DynamicLayout);
        DynamicLayout.setHorizontalGroup(
            DynamicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DynamicLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 661, Short.MAX_VALUE))
        );
        DynamicLayout.setVerticalGroup(
            DynamicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DynamicLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(Dynamic, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1AddDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AddDActionPerformed
        // TODO add your handling code here:
         p1.setVisible(true);
    p2.setVisible(false);
    p3.setVisible(false);
    }//GEN-LAST:event_jButton1AddDActionPerformed

    private void jButton2ListDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ListDActionPerformed
        // TODO add your handling code here:
     p1.setVisible(false);
    p2.setVisible(true);
    p3.setVisible(false);
    }//GEN-LAST:event_jButton2ListDActionPerformed

    private void jButtonupdateDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonupdateDActionPerformed
        // TODO add your handling code here:
         p1.setVisible(false);
    p2.setVisible(false);
    p3.setVisible(true);
    }//GEN-LAST:event_jButtonupdateDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dynamic;
    private javax.swing.JButton jButton1AddD;
    private javax.swing.JButton jButton2ListD;
    private javax.swing.JButton jButtonupdateD;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
